name: Generate Pastel Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Anannyaa15
          outputs: |
            dist/snake.svg?palette=github-light&color_snake=ff9ecf&color_dots=#fce4ec,#f8bbd0,#f48fb1,#f06292,#ec407a

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
